name = "knotify-telegram"
type = "webpack"
zone_id = "d4023c8469ec22a1a8606c2f15edd0e8"
account_id = "595a22d447b6f579a3bac7613e8aec5e"
route = "knotify.miao.dev/*"
workers_dev = true
webpack_config = "webpack.config.js"